item_types:
    sylius_product:
        name: item_types.sylius_product
        preview:
            template: '%netgen_content_browser.sylius_product.item_template%'
        columns:
            name:
                name: columns.name
                value_provider: name
            price:
                name: columns.sylius_product.price
                template: '%netgen_content_browser.sylius_product.price_template%'
            product_id:
                name: columns.sylius_product.product_id
                value_provider: sylius_product\product_id
        default_columns:
            - name
            - price
