services:
    netgen_content_browser.backend.sylius_product:
        class: Netgen\ContentBrowser\Sylius\Backend\ProductBackend
        arguments:
            - "@sylius.repository.taxon"
            - "@sylius.repository.product"
            - "@netgen_content_browser.sylius.service.product"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: sylius_product }

    netgen_content_browser.backend.sylius_taxon:
        class: Netgen\ContentBrowser\Sylius\Backend\TaxonBackend
        arguments:
            - "@sylius.repository.taxon"
            - "@netgen_content_browser.sylius.service.taxon"
            - "@sylius.context.locale"
        tags:
            - { name: netgen_content_browser.backend, item_type: sylius_taxon }
