parameters:
    netgen_content_browser.sylius_product.item_template: '@@NetgenContentBrowserSylius/product_item.html.twig'
    netgen_content_browser.sylius_product.price_template: '@@NetgenContentBrowserSylius/columns/price.html.twig'
    netgen_content_browser.sylius_taxon.item_template: '@@NetgenContentBrowserSylius/taxon_item.html.twig'
